# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\AN24\branches\simulation version\Holter_mother_edition2.6\_eric4project\FillPatient.ui'
#
# Created: Mon Jan 11 23:00:08 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_FillPatient(object):
    def setupUi(self, FillPatient):
        FillPatient.setObjectName(_fromUtf8("FillPatient"))
        FillPatient.resize(593, 334)
        FillPatient.setStyleSheet(_fromUtf8(""))
        self.formLayoutWidget = QtGui.QWidget(FillPatient)
        self.formLayoutWidget.setGeometry(QtCore.QRect(30, 20, 541, 276))
        self.formLayoutWidget.setObjectName(_fromUtf8("formLayoutWidget"))
        self.formLayout = QtGui.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.ExpandingFieldsGrow)
        self.formLayout.setRowWrapPolicy(QtGui.QFormLayout.DontWrapRows)
        self.formLayout.setMargin(0)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_Name = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Name.sizePolicy().hasHeightForWidth())
        self.label_Name.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Name.setFont(font)
        self.label_Name.setObjectName(_fromUtf8("label_Name"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_Name)
        self.label_Age = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Age.sizePolicy().hasHeightForWidth())
        self.label_Age.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Age.setFont(font)
        self.label_Age.setObjectName(_fromUtf8("label_Age"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_Age)
        self.label_Weeks = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Weeks.sizePolicy().hasHeightForWidth())
        self.label_Weeks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Weeks.setFont(font)
        self.label_Weeks.setObjectName(_fromUtf8("label_Weeks"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_Weeks)
        self.lineEdit_Weeks = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Weeks.sizePolicy().hasHeightForWidth())
        self.lineEdit_Weeks.setSizePolicy(sizePolicy)
        self.lineEdit_Weeks.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Weeks.setObjectName(_fromUtf8("lineEdit_Weeks"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.lineEdit_Weeks)
        self.label_Outpatient_NO = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Outpatient_NO.sizePolicy().hasHeightForWidth())
        self.label_Outpatient_NO.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Outpatient_NO.setFont(font)
        self.label_Outpatient_NO.setObjectName(_fromUtf8("label_Outpatient_NO"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_Outpatient_NO)
        self.lineEdit_Outpatient_NO = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Outpatient_NO.sizePolicy().hasHeightForWidth())
        self.lineEdit_Outpatient_NO.setSizePolicy(sizePolicy)
        self.lineEdit_Outpatient_NO.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Outpatient_NO.setObjectName(_fromUtf8("lineEdit_Outpatient_NO"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.lineEdit_Outpatient_NO)
        self.lineEdit_Hospitalization_NO = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Hospitalization_NO.sizePolicy().hasHeightForWidth())
        self.lineEdit_Hospitalization_NO.setSizePolicy(sizePolicy)
        self.lineEdit_Hospitalization_NO.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Hospitalization_NO.setObjectName(_fromUtf8("lineEdit_Hospitalization_NO"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.lineEdit_Hospitalization_NO)
        self.label_Bed_NO = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Bed_NO.sizePolicy().hasHeightForWidth())
        self.label_Bed_NO.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Bed_NO.setFont(font)
        self.label_Bed_NO.setObjectName(_fromUtf8("label_Bed_NO"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_Bed_NO)
        self.label_Guardianship_NO = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Guardianship_NO.sizePolicy().hasHeightForWidth())
        self.label_Guardianship_NO.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Guardianship_NO.setFont(font)
        self.label_Guardianship_NO.setObjectName(_fromUtf8("label_Guardianship_NO"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_Guardianship_NO)
        self.lineEdit_Guardianship_NO = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Guardianship_NO.sizePolicy().hasHeightForWidth())
        self.lineEdit_Guardianship_NO.setSizePolicy(sizePolicy)
        self.lineEdit_Guardianship_NO.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Guardianship_NO.setObjectName(_fromUtf8("lineEdit_Guardianship_NO"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.lineEdit_Guardianship_NO)
        self.label_Hospitalization_NO = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Hospitalization_NO.sizePolicy().hasHeightForWidth())
        self.label_Hospitalization_NO.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Hospitalization_NO.setFont(font)
        self.label_Hospitalization_NO.setObjectName(_fromUtf8("label_Hospitalization_NO"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_Hospitalization_NO)
        self.lineEdit_Bed_NO = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Bed_NO.sizePolicy().hasHeightForWidth())
        self.lineEdit_Bed_NO.setSizePolicy(sizePolicy)
        self.lineEdit_Bed_NO.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Bed_NO.setObjectName(_fromUtf8("lineEdit_Bed_NO"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.lineEdit_Bed_NO)
        self.label_Name_2 = QtGui.QLabel(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Name_2.sizePolicy().hasHeightForWidth())
        self.label_Name_2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Microsoft YaHei UI"))
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_Name_2.setFont(font)
        self.label_Name_2.setObjectName(_fromUtf8("label_Name_2"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_Name_2)
        self.lineEdit_Name = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Name.sizePolicy().hasHeightForWidth())
        self.lineEdit_Name.setSizePolicy(sizePolicy)
        self.lineEdit_Name.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Name.setObjectName(_fromUtf8("lineEdit_Name"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEdit_Name)
        self.lineEdit_Age = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Age.sizePolicy().hasHeightForWidth())
        self.lineEdit_Age.setSizePolicy(sizePolicy)
        self.lineEdit_Age.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEdit_Age.setObjectName(_fromUtf8("lineEdit_Age"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEdit_Age)
        self.lineEdit_Person_No = QtGui.QLineEdit(self.formLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_Person_No.sizePolicy().hasHeightForWidth())
        self.lineEdit_Person_No.setSizePolicy(sizePolicy)
        self.lineEdit_Person_No.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.lineEdit_Person_No.setObjectName(_fromUtf8("lineEdit_Person_No"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEdit_Person_No)
        self.pushButton_OK = QtGui.QPushButton(FillPatient)
        self.pushButton_OK.setEnabled(False)
        self.pushButton_OK.setGeometry(QtCore.QRect(130, 290, 75, 23))
        self.pushButton_OK.setObjectName(_fromUtf8("pushButton_OK"))
        self.pushButton_Reset = QtGui.QPushButton(FillPatient)
        self.pushButton_Reset.setGeometry(QtCore.QRect(370, 290, 75, 23))
        self.pushButton_Reset.setObjectName(_fromUtf8("pushButton_Reset"))

        self.retranslateUi(FillPatient)
        QtCore.QMetaObject.connectSlotsByName(FillPatient)

    def retranslateUi(self, FillPatient):
        FillPatient.setWindowTitle(_translate("FillPatient", "Dialog", None))
        self.label_Name.setText(_translate("FillPatient", "Name:", None))
        self.label_Age.setText(_translate("FillPatient", "Age:", None))
        self.label_Weeks.setText(_translate("FillPatient", "Weeks:", None))
        self.label_Outpatient_NO.setText(_translate("FillPatient", "Outpatient NO:", None))
        self.label_Bed_NO.setText(_translate("FillPatient", "Bed NO:", None))
        self.label_Guardianship_NO.setText(_translate("FillPatient", "Guardianship NO:", None))
        self.label_Hospitalization_NO.setText(_translate("FillPatient", "Hospitalization NO:", None))
        self.label_Name_2.setText(_translate("FillPatient", "<html><head/><body><p><span style=\" color:#ff0000;\">*</span>Person NO:</p></body></html>", None))
        self.pushButton_OK.setText(_translate("FillPatient", "OK", None))
        self.pushButton_Reset.setText(_translate("FillPatient", "Reset", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    FillPatient = QtGui.QDialog()
    ui = Ui_FillPatient()
    ui.setupUi(FillPatient)
    FillPatient.show()
    sys.exit(app.exec_())

