# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\AN24\branches\simulation version\Holter_mother_edition2.6\_eric4project\Settings.ui'
#
# Created: Thu Jan 14 14:31:19 2016
#      by: PyQt4 UI code generator 4.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Settings(object):
    def setupUi(self, Settings):
        Settings.setObjectName(_fromUtf8("Settings"))
        Settings.resize(352, 275)
        Settings.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabWidget = QtGui.QTabWidget(Settings)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 331, 221))
        self.tabWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(255, 128, 128);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.switch = QtGui.QWidget()
        self.switch.setObjectName(_fromUtf8("switch"))
        self.label_6 = QtGui.QLabel(self.switch)
        self.label_6.setGeometry(QtCore.QRect(20, 50, 91, 16))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.horizontalLayoutWidget_2 = QtGui.QWidget(self.switch)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(130, 50, 160, 21))
        self.horizontalLayoutWidget_2.setObjectName(_fromUtf8("horizontalLayoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.radioAlarmOn = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioAlarmOn.setObjectName(_fromUtf8("radioAlarmOn"))
        self.horizontalLayout_2.addWidget(self.radioAlarmOn)
        self.radioAlarmOff = QtGui.QRadioButton(self.horizontalLayoutWidget_2)
        self.radioAlarmOff.setObjectName(_fromUtf8("radioAlarmOff"))
        self.horizontalLayout_2.addWidget(self.radioAlarmOff)
        self.label_7 = QtGui.QLabel(self.switch)
        self.label_7.setGeometry(QtCore.QRect(20, 80, 91, 16))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayoutWidget_3 = QtGui.QWidget(self.switch)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(130, 80, 160, 21))
        self.horizontalLayoutWidget_3.setObjectName(_fromUtf8("horizontalLayoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.radioHeartOn = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioHeartOn.setObjectName(_fromUtf8("radioHeartOn"))
        self.horizontalLayout_3.addWidget(self.radioHeartOn)
        self.radioHeartOff = QtGui.QRadioButton(self.horizontalLayoutWidget_3)
        self.radioHeartOff.setObjectName(_fromUtf8("radioHeartOff"))
        self.horizontalLayout_3.addWidget(self.radioHeartOff)
        self.tabWidget.addTab(self.switch, _fromUtf8(""))
        self.view = QtGui.QWidget()
        self.view.setObjectName(_fromUtf8("view"))
        self.formLayoutWidget_2 = QtGui.QWidget(self.view)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(20, 20, 281, 101))
        self.formLayoutWidget_2.setObjectName(_fromUtf8("formLayoutWidget_2"))
        self.formLayout_2 = QtGui.QFormLayout(self.formLayoutWidget_2)
        self.formLayout_2.setMargin(0)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.label = QtGui.QLabel(self.formLayoutWidget_2)
        self.label.setObjectName(_fromUtf8("label"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.label)
        self.lineEditTop = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditTop.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditTop.setObjectName(_fromUtf8("lineEditTop"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.lineEditTop)
        self.label_3 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.label_2 = QtGui.QLabel(self.formLayoutWidget_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_2)
        self.lineEditUpper = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditUpper.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditUpper.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditUpper.setObjectName(_fromUtf8("lineEditUpper"))
        self.formLayout_2.setWidget(1, QtGui.QFormLayout.FieldRole, self.lineEditUpper)
        self.lineEditLower = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditLower.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditLower.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditLower.setObjectName(_fromUtf8("lineEditLower"))
        self.formLayout_2.setWidget(2, QtGui.QFormLayout.FieldRole, self.lineEditLower)
        self.lineEditBottom = QtGui.QLineEdit(self.formLayoutWidget_2)
        self.lineEditBottom.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditBottom.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditBottom.setObjectName(_fromUtf8("lineEditBottom"))
        self.formLayout_2.setWidget(3, QtGui.QFormLayout.FieldRole, self.lineEditBottom)
        self.label_5 = QtGui.QLabel(self.view)
        self.label_5.setGeometry(QtCore.QRect(20, 130, 61, 16))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.view)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(110, 130, 160, 21))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.radioXy1 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioXy1.setStyleSheet(_fromUtf8(""))
        self.radioXy1.setChecked(True)
        self.radioXy1.setObjectName(_fromUtf8("radioXy1"))
        self.horizontalLayout.addWidget(self.radioXy1)
        self.radioXy2 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioXy2.setObjectName(_fromUtf8("radioXy2"))
        self.horizontalLayout.addWidget(self.radioXy2)
        self.radioXy3 = QtGui.QRadioButton(self.horizontalLayoutWidget)
        self.radioXy3.setObjectName(_fromUtf8("radioXy3"))
        self.horizontalLayout.addWidget(self.radioXy3)
        self.label_8 = QtGui.QLabel(self.view)
        self.label_8.setGeometry(QtCore.QRect(20, 160, 81, 16))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.lineEditScrRatio = QtGui.QLineEdit(self.view)
        self.lineEditScrRatio.setGeometry(QtCore.QRect(110, 160, 195, 20))
        self.lineEditScrRatio.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.lineEditScrRatio.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditScrRatio.setObjectName(_fromUtf8("lineEditScrRatio"))
        self.tabWidget.addTab(self.view, _fromUtf8(""))
        self.printer = QtGui.QWidget()
        self.printer.setObjectName(_fromUtf8("printer"))
        self.horizontalLayoutWidget_4 = QtGui.QWidget(self.printer)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(40, 10, 241, 22))
        self.horizontalLayoutWidget_4.setObjectName(_fromUtf8("horizontalLayoutWidget_4"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_minutes = QtGui.QLabel(self.horizontalLayoutWidget_4)
        self.label_minutes.setObjectName(_fromUtf8("label_minutes"))
        self.horizontalLayout_4.addWidget(self.label_minutes)
        self.lineEditMinutes = QtGui.QLineEdit(self.horizontalLayoutWidget_4)
        self.lineEditMinutes.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.lineEditMinutes.setObjectName(_fromUtf8("lineEditMinutes"))
        self.horizontalLayout_4.addWidget(self.lineEditMinutes)
        self.tabWidget.addTab(self.printer, _fromUtf8(""))
        self.note = QtGui.QWidget()
        self.note.setObjectName(_fromUtf8("note"))
        self.tabWidget.addTab(self.note, _fromUtf8(""))
        self.pushButtonOK = QtGui.QPushButton(Settings)
        self.pushButtonOK.setGeometry(QtCore.QRect(210, 240, 61, 26))
        self.pushButtonOK.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonOK.setStyleSheet(_fromUtf8("background-image: url(:/picture/imgs/button_ok.png);\n"
"background-repeat:no-repeat;"))
        self.pushButtonOK.setFlat(True)
        self.pushButtonOK.setObjectName(_fromUtf8("pushButtonOK"))
        self.pushButtonCancel = QtGui.QPushButton(Settings)
        self.pushButtonCancel.setGeometry(QtCore.QRect(280, 240, 61, 26))
        self.pushButtonCancel.setFocusPolicy(QtCore.Qt.NoFocus)
        self.pushButtonCancel.setStyleSheet(_fromUtf8("background-image: url(:/picture/imgs/button_ok.png);\n"
"background-repeat:no-repeat;"))
        self.pushButtonCancel.setFlat(True)
        self.pushButtonCancel.setObjectName(_fromUtf8("pushButtonCancel"))

        self.retranslateUi(Settings)
        self.tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(Settings)

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(_translate("Settings", "Dialog", None))
        self.label_6.setText(_translate("Settings", "is_alarm_sound::", None))
        self.radioAlarmOn.setText(_translate("Settings", "ON", None))
        self.radioAlarmOff.setText(_translate("Settings", "OFF", None))
        self.label_7.setText(_translate("Settings", "is_heart_sound::", None))
        self.radioHeartOn.setText(_translate("Settings", "ON", None))
        self.radioHeartOff.setText(_translate("Settings", "OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.switch), _translate("Settings", "switch", None))
        self.label.setText(_translate("Settings", "top_limit:", None))
        self.lineEditTop.setText(_translate("Settings", "180", None))
        self.label_3.setText(_translate("Settings", "upper_limit:", None))
        self.label_4.setText(_translate("Settings", "lower_limit:", None))
        self.label_2.setText(_translate("Settings", "bottom_limit:", None))
        self.lineEditUpper.setText(_translate("Settings", "140", None))
        self.lineEditLower.setText(_translate("Settings", "110", None))
        self.lineEditBottom.setText(_translate("Settings", "80", None))
        self.label_5.setText(_translate("Settings", "xyRatio:", None))
        self.radioXy1.setText(_translate("Settings", "1", None))
        self.radioXy2.setText(_translate("Settings", "2", None))
        self.radioXy3.setText(_translate("Settings", "3", None))
        self.label_8.setText(_translate("Settings", "screen_ratio:", None))
        self.lineEditScrRatio.setText(_translate("Settings", "0.8", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.view), _translate("Settings", "view", None))
        self.label_minutes.setText(_translate("Settings", "Minutes:", None))
        self.lineEditMinutes.setText(_translate("Settings", "20", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.printer), _translate("Settings", "printer", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.note), _translate("Settings", "note", None))
        self.pushButtonOK.setText(_translate("Settings", "ok", None))
        self.pushButtonCancel.setText(_translate("Settings", "cancel", None))

import images_rc

if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    Settings = QtGui.QDialog()
    ui = Ui_Settings()
    ui.setupUi(Settings)
    Settings.show()
    sys.exit(app.exec_())

